//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pearproduction
    {
        public int id { get; set; }
        public string country_name { get; set; }
        public Nullable<int> production_2020 { get; set; }
        public Nullable<int> production_2019 { get; set; }
        public Nullable<int> production_2018 { get; set; }
    }
}
